version: "3.9"

name: qtim

services:
  nuxt:
    container_name: qtim-f-nuxt
    build:
      context: ../frontend
      dockerfile: ../docker/local/Dockerfile
      args:
        GID: ${GID}
        UID: ${UID}
        PORT: 3000
        NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"
    volumes:
      - ../frontend/:/var/www/frontend
    networks:
      - qtim

networks:
  qtim:
    driver: bridge
