version: "3.9"

name: qtim

services:
  nuxt:
    container_name: qtim-f-nuxt
    build:
      context: ../frontend
      dockerfile: ../docker/local/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        PORT: ${PORT}
        NODE_ENV: ${NODE_ENV}
    ports:
      - '3000:3000'
    volumes:
      - ../frontend:/var/www/client
      - /var/www/client/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - qtim

networks:
  qtim:
    driver: bridge
